version: 2.1

workflows:
  main:
    jobs:
      - build

  weekly:
    jobs:
      - build
    triggers:
      - schedule:
          # run at 00:30 every Sunday
          cron: "30 0 * * 0"
          filters:
            branches:
              only:
                - main

jobs:
  build:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout

      - run:
          name: "Install tox"
          command: python -I -m pip install tox

      - run:
          name: "Run tox"
          command: python -m tox
