version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout

      - run:
          name: "Install tox"
          command: python -I -m pip install tox

      - run:
          name: "Run tox"
          command: python -m tox
