name: lig3dlens

channels:
  - rdkit
  - pytorch
  - psi4
  - conda-forge

dependencies:
  - python>=3.9
  - rdkit
  - black
  - isort
  - pytorch
  - numpy
  - scikit-learn
  - datamol
  - molfeat
  - scipy
  - matplotlib
  - joblib
  - loguru
  - tqdm
  - jupyter
  - pytest
  - py3dmol
  - psi4
  - resp
  - pip
  - pip:
    - git+https://github.com/hesther/chemprop-atom-bond.git@09a2e32636bbd252c26a28d06ff865e364e398bf
    - git+https://github.com/hesther/espsim.git@533a53105858d1a25cbe2fb54dd7208d7989caa1